/** Declaration file generated by dts-gen */

export = cws_flitui;

declare const cws_flitui: {
    Alert: {
        computed: {
            typeClass: any;
        };
        data: any;
        methods: {
            close: any;
        };
        props: {
            autoClose: {
                default: boolean;
                type: any;
            };
            closable: {
                default: boolean;
                type: any;
            };
            message: {
                required: boolean;
                type: any;
            };
            modelValue: {
                default: boolean;
                type: any;
            };
            top: {
                default: boolean;
                type: any;
            };
            type: {
                default: string;
                type: any;
                validator: any;
            };
        };
        render: any;
        watch: {
            modelValue: any;
        };
    };
    Button: {
        props: {
            disabled: {
                default: boolean;
                type: any;
            };
            kind: {
                default: string;
                type: any;
            };
            level: {
                default: string;
                type: any;
            };
            loading: {
                default: boolean;
                type: any;
            };
            size: {
                default: string;
                type: any;
            };
        };
        render: any;
        setup: any;
    };
    Dialogue: {
        components: {
            Button: {
                props: {
                    disabled: {
                        default: boolean;
                        type: any;
                    };
                    kind: {
                        default: string;
                        type: any;
                    };
                    level: {
                        default: string;
                        type: any;
                    };
                    loading: {
                        default: boolean;
                        type: any;
                    };
                    size: {
                        default: string;
                        type: any;
                    };
                };
                render: any;
                setup: any;
            };
        };
        emits: string[];
        props: {
            cancel: {
                type: any;
            };
            confirm: {
                type: any;
            };
            modelValue: {
                default: boolean;
                type: any;
            };
            onClickOverlay: {
                default: boolean;
                type: any;
            };
            title: {
                default: string;
                type: any;
            };
        };
        render: any;
        setup: any;
    };
    Switch: {
        emits: string[];
        props: {
            disabled: {
                default: boolean;
                type: any;
            };
            modelValue: any;
        };
        render: any;
        setup: any;
    };
    Tab: {
        render: any;
    };
    Tabs: {
        props: {
            modelValue: {
                type: any;
            };
        };
        render: any;
        setup: any;
    };
};

